### ISSUE TITLE
Node 4 Support

### ISSUE THREAD

**Issue by hbetts** [bahmutov/ggit#58]
A recent version of `npm-utils` began depending on `ggit`.

`ggit`, and at least two of it's dependencies, `snap-shot-core` and `schema-shot`, use ES6+ features only available in Node 6.

Therefore I've found myself in a situation where I can't upgrade any of my projects to use newer versions of `npm-utils` (as I still support Node 4).

At the moment, the time to submit pull requests against all Node 6 projects would be extensive, and I'm not sure it's worth it at this point. It would either require writing, and re-writing, all code constrained to Node 4 only features, or setting up all projects with a compiler to transpile ES6+ code to something that is compatible with Node 4.

**Comment by bahmutov** [comment]
Boo, problem is that even if I setup babel transpile, it has to be done everywhere, including dependencies.

**Comment by hbetts** [comment]
@bahmutov, yes, which is why I am a little concerned. The `ggit` dependencies are quite extensive, and to support Node 4, while having support for most ES6+ features, would require extensive work on either of our parts to carry out, and on your part (simply because you would have more infrastructure to support in projects you're maintaining) to maintain long term.

As a solution that allows me to move forward, I'm going to see if I can replicate the `setAuthToken` functionality of `npm-utils` in a separate package with Node 4 tests. Then perhaps I can submit a pull request against `npm-utils` to have it depend on that package for just the `setAuthToken` feature.

**Comment by bahmutov** [comment]
I say, small small modules are the best. But I am also thinking if we could roll all dependencies into single bundle and transpile it into Node4?
