### ISSUE TITLE
Delete History.md

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/ggit#67]
Or just direct to GitHub releases

**Comment by hbetts** [comment]
On several work-related projects I maintain a `CHANGELOG.md` file for the sole purpose of providing a link to the _Releases_ page. Looking for a `CHANGELOG.md` file is pretty standard for developers, yet I use GitHub or GitLab _Release_ pages now.

**Comment by bahmutov** [comment]
Version `2.4.2` has been published to NPM. The full release note can be found at [ggit/releases/tag/v2.4.2](https://github.com/bahmutov/ggit/releases/tag/v2.4.2).

**Tip:** safely upgrade dependency ggit in your project using [next-update](https://github.com/bahmutov/next-update)
